# Generated by Django 4.0.5 on 2022-06-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageFiles', '0004_remove_file_file_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='FileCreationDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_class',
            field=models.CharField(blank=True, choices=[('ক', 'ক'), ('খ', 'খ'), ('গ', 'গ'), ('ঘ', 'ঘ')], max_length=10, null=True),
        ),
    ]
